In [3]:
#url = https://drive.google.com/u/1/uc?id=1Wt1eQkZz76gqRL9h8R6FOEPH3eLsbLsA&export=download

In [4]:
!pip install gdown

In [5]:
import gdown
dataset_url = "https://drive.google.com/u/1/uc?id=1Wt1eQkZz76gqRL9h8R6FOEPH3eLsbLsA&export=download"
filename = "./healthcare-dataset-stroke-data.csv"
gdown.download(dataset_url,filename)

Downloading...
From: https://drive.google.com/u/1/uc?id=1Wt1eQkZz76gqRL9h8R6FOEPH3eLsbLsA&export=download
To: C:\Users\absol\Desktop\ML BootCamp\healthcare-dataset-stroke-data.csv
100%|███████████████████████████████████████████████████████████████████████████████| 317k/317k [00:00<00:00, 1.23MB/s]


'./healthcare-dataset-stroke-data.csv'

## [Library] NumPy

## [Library] Pandas

In [6]:
!pip install numpy #This is for VS code
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn

ERROR: Invalid requirement: '#This'


In [7]:
import pandas as pd
df = pd.read_csv("healthcare-dataset-stroke-data.csv")
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

1D-Series
2D-dataframe

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


## Numerical Variable

In [9]:
round(df.describe(exclude='object'),2)

id      age  hypertension  heart_disease  avg_glucose_level  \
count   5110.00  5110.00        5110.0        5110.00            5110.00   
mean   36517.83    43.23           0.1           0.05             106.15   
std    21161.72    22.61           0.3           0.23              45.28   
min       67.00     0.08           0.0           0.00              55.12   
25%    17741.25    25.00           0.0           0.00              77.24   
50%    36932.00    45.00           0.0           0.00              91.88   
75%    54682.00    61.00           0.0           0.00             114.09   
max    72940.00    82.00           1.0           1.00             271.74   

           bmi   stroke  
count  4909.00  5110.00  
mean     28.89     0.05  
std       7.85     0.22  
min      10.30     0.00  
25%      23.50     0.00  
50%      28.10     0.00  
75%      33.10     0.00  
max      97.60     1.00

In [11]:
round(df.describe(exclude = ['float', 'int64']),2) #Categorical

gender ever_married work_type Residence_type smoking_status
count     5110         5110      5110           5110           5110
unique       3            2         5              2              4
top     Female          Yes   Private          Urban   never smoked
freq      2994         3353      2925           2596           1892

In [12]:
df['gender'].value_counts()

Female    2994
Male      2115
Other        1
Name: gender, dtype: int64

In [13]:
df[df.gender != "Other"]

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5109 rows x 12 columns]

In [14]:
df = df[df.gender != "Other"]
df['gender'].value_counts()

Female    2994
Male      2115
Name: gender, dtype: int64

In [15]:
df.hypertension.unique()

array([0, 1], dtype=int64)

In [16]:
df.heart_disease.unique()

array([1, 0], dtype=int64)

## Analysis on age

In [17]:
df.age.min()

0.08

In [18]:
df.age.max()

82.0

In [19]:
df[df.age <= 10].describe()

id         age  hypertension  heart_disease  \
count    507.000000  507.000000         507.0     507.000000   
mean   35535.270217    4.670611           0.0       0.001972   
std    21043.985044    3.031630           0.0       0.044412   
min      172.000000    0.080000           0.0       0.000000   
25%    16544.500000    2.000000           0.0       0.000000   
50%    34436.000000    4.000000           0.0       0.000000   
75%    53883.500000    8.000000           0.0       0.000000   
max    72940.000000   10.000000           0.0       1.000000   

       avg_glucose_level         bmi      stroke  
count          507.00000  493.000000  507.000000  
mean            92.96432   18.923732    0.001972  
std             25.12137    3.636058    0.044412  
min             55.34000   10.300000    0.000000  
25%             76.12000   16.700000    0.000000  
50%             88.83000   18.300000    0.000000  
75%            107.13500   20.100000    0.000000  
max            206.25000   35.200000    1.000000

In [20]:
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [21]:
df.iloc[0:5, [1,2,11]]

gender   age  stroke
0    Male  67.0       1
1  Female  61.0       1
2    Male  80.0       1
3  Female  49.0       1
4  Female  79.0       1

In [22]:
df.iloc[0:5, ['gender','age','stroke']]

IndexError: .iloc requires numeric indexers, got ['gender' 'age' 'stroke']

In [23]:
age_chunk = df.loc[df.age <= 10]
age_chunk

id  gender   age  hypertension  heart_disease ever_married work_type  \
162   69768  Female  1.32             0              0           No  children   
249   30669    Male  3.00             0              0           No  children   
251   16523  Female  8.00             0              0           No   Private   
282   33759  Female  3.00             0              0           No  children   
291   11014    Male  4.00             0              0           No  children   
...     ...     ...   ...           ...            ...          ...       ...   
5078  27446  Female  8.00             0              0           No  children   
5079  42709    Male  1.72             0              0           No  children   
5089  56714  Female  0.72             0              0           No  children   
5095  68598    Male  1.08             0              0           No  children   
5098    579    Male  9.00             0              0           No  children   

     Residence_type  avg_glucose_level   bmi smoking_status  stroke  
162           Urban              70.37   NaN        Unknown       1  
249           Rural              95.12  18.0        Unknown       0  
251           Urban             110.89  17.6        Unknown       0  
282           Urban              73.74  16.0        Unknown       0  
291           Rural              79.17  20.0        Unknown       0  
...             ...                ...   ...            ...     ...  
5078          Urban              76.31  15.5        Unknown       0  
5079          Urban              77.28  17.1        Unknown       0  
5089          Rural              62.13  16.8        Unknown       0  
5095          Rural              79.15  17.4        Unknown       0  
5098          Urban              71.88  17.5        Unknown       0  

[507 rows x 12 columns]

In [24]:
age_chunk.tail(3)

id  gender   age  hypertension  heart_disease ever_married work_type  \
5089  56714  Female  0.72             0              0           No  children   
5095  68598    Male  1.08             0              0           No  children   
5098    579    Male  9.00             0              0           No  children   

     Residence_type  avg_glucose_level   bmi smoking_status  stroke  
5089          Rural              62.13  16.8        Unknown       0  
5095          Rural              79.15  17.4        Unknown       0  
5098          Urban              71.88  17.5        Unknown       0

In [25]:
age_chunk.hypertension.unique()

array([0], dtype=int64)

In [26]:
age_chunk.heart_disease.unique()

array([0, 1], dtype=int64)

In [27]:
age_chunk.loc[age_chunk.heart_disease ==1]

id gender  age  hypertension  heart_disease ever_married work_type  \
3031  65688   Male  2.0             0              1           No  children   

     Residence_type  avg_glucose_level   bmi smoking_status  stroke  
3031          Urban              62.89  29.4        Unknown       0

In [28]:
age_chunk.ever_married.unique()

array(['No'], dtype=object)

In [29]:
age_chunk.loc[age_chunk.work_type == 'Self-employed']

id gender  age  hypertension  heart_disease ever_married  \
410  54975   Male  7.0             0              0           No   

         work_type Residence_type  avg_glucose_level   bmi smoking_status  \
410  Self-employed          Rural              64.06  18.9        Unknown   

     stroke  
410       0

In [30]:
age_chunk.stroke.value_counts()

0    506
1      1
Name: stroke, dtype: int64

In [31]:
age_chunk.smoking_status.value_counts()

Unknown            497
never smoked         5
formerly smoked      4
smokes               1
Name: smoking_status, dtype: int64

## EDA and Data cleaning

In [32]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [33]:
df.bmi.head()

0    36.6
1     NaN
2    32.5
3    34.4
4    24.0
Name: bmi, dtype: float64

In [34]:
df.isna().transpose()

0      1      2      3      4      5      6      7     \
id                 False  False  False  False  False  False  False  False   
gender             False  False  False  False  False  False  False  False   
age                False  False  False  False  False  False  False  False   
hypertension       False  False  False  False  False  False  False  False   
heart_disease      False  False  False  False  False  False  False  False   
ever_married       False  False  False  False  False  False  False  False   
work_type          False  False  False  False  False  False  False  False   
Residence_type     False  False  False  False  False  False  False  False   
avg_glucose_level  False  False  False  False  False  False  False  False   
bmi                False   True  False  False  False  False  False  False   
smoking_status     False  False  False  False  False  False  False  False   
stroke             False  False  False  False  False  False  False  False   

                    8      9     ...   5100   5101   5102   5103   5104  \
id                 False  False  ...  False  False  False  False  False   
gender             False  False  ...  False  False  False  False  False   
age                False  False  ...  False  False  False  False  False   
hypertension       False  False  ...  False  False  False  False  False   
heart_disease      False  False  ...  False  False  False  False  False   
ever_married       False  False  ...  False  False  False  False  False   
work_type          False  False  ...  False  False  False  False  False   
Residence_type     False  False  ...  False  False  False  False  False   
avg_glucose_level  False  False  ...  False  False  False  False  False   
bmi                 True  False  ...  False  False  False  False  False   
smoking_status     False  False  ...  False  False  False  False  False   
stroke             False  False  ...  False  False  False  False  False   

                    5105   5106   5107   5108   5109  
id                 False  False  False  False  False  
gender             False  False  False  False  False  
age                False  False  False  False  False  
hypertension       False  False  False  False  False  
heart_disease      False  False  False  False  False  
ever_married       False  False  False  False  False  
work_type          False  False  False  False  False  
Residence_type     False  False  False  False  False  
avg_glucose_level  False  False  False  False  False  
bmi                 True  False  False  False  False  
smoking_status     False  False  False  False  False  
stroke             False  False  False  False  False  

[12 rows x 5109 columns]

## Univariate anialysis
## bivariate

In [35]:
import seaborn as sns

## Nisha pokharel

In [ ]:
hello, I am nisha pokharel. I am currently learning machine learning and data science and also doing project on it. 